version: "3.8"

services:
  onquadro-database:
    image: postgres:14
    volumes:
      - /mnt/data1/tzok/onquadro-postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PGUSER:-qbase}
      - POSTGRES_PASSWORD=${PGPASSWORD:-Jellux37}
      - POSTGRES_DB=${PGDATABASE:-qbase}

  onquadro-frontend:
    build: .
    ports:
      - 8080:80
    volumes:
      - /mnt/data1/tzok/onquadro-wwwroot/onquadro_plots:/RNAqbase/wwwroot/onquadro_plots
      - /mnt/data1/tzok/onquadro-wwwroot/static/layers:/RNAqbase/wwwroot/static/layers
      - /mnt/data1/tzok/onquadro-wwwroot/static/pymol:/RNAqbase/wwwroot/static/pymol
      - /mnt/data1/tzok/onquadro-wwwroot/static/rchie:/RNAqbase/wwwroot/static/rchie
      - /mnt/data1/tzok/onquadro-wwwroot/static/varna:/RNAqbase/wwwroot/static/varna
